# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PiCar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(238, 148)
        self.inputspeed = QtWidgets.QLineEdit(Dialog)
        self.inputspeed.setGeometry(QtCore.QRect(20, 20, 113, 20))
        self.inputspeed.setObjectName("inputspeed")
        self.inputangle = QtWidgets.QLineEdit(Dialog)
        self.inputangle.setGeometry(QtCore.QRect(20, 50, 113, 20))
        self.inputangle.setObjectName("inputangle")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 20, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(140, 50, 61, 16))
        self.label_2.setObjectName("label_2")
        self.run = QtWidgets.QPushButton(Dialog)
        self.run.setGeometry(QtCore.QRect(20, 110, 75, 23))
        self.run.setObjectName("run")
        self.stop = QtWidgets.QPushButton(Dialog)
        self.stop.setGeometry(QtCore.QRect(100, 110, 75, 23))
        self.stop.setObjectName("stop")
        self.inputdirection = QtWidgets.QLineEdit(Dialog)
        self.inputdirection.setGeometry(QtCore.QRect(20, 80, 113, 20))
        self.inputdirection.setObjectName("inputdirection")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(140, 80, 51, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Gerschwindigkeit"))
        self.label_2.setText(_translate("Dialog", "Lenkwinkel"))
        self.run.setText(_translate("Dialog", "Los"))
        self.stop.setText(_translate("Dialog", "Stop"))
        self.label_3.setText(_translate("Dialog", "Richtung"))
